<div class="header-container layout-8 sticky-header">
	<div class="header panel flex-layout-sticky center_vertical no-wrap-desktop">
		<div class="flex-layout space-between center_vertical no-wrap-desktop header-middle">
			<div class="logo-container">
				<div class="logo-site">
					<?php echo $this->getChildHtml('logo'); ?>
				</div>
			</div>
			<div class="top-search-not-dropdown button-search-full">
				<?php echo $this->getChildHtml("mageworx-search-autocomplete-wrapper"); ?>
			</div>
			<div class="col-action col-right">
				<div class="flex-layout center_vertical">
					<ul class="flex-layout action-header center_vertical no-wrap-desktop">
						<li class="account-link-header hidden-xs">
							<?php echo $this->getChildHtml("top.links"); ?>
						</li>
						<?php echo $block->getLayout()->createBlock('Magento\Wishlist\Block\Link')->setTemplate('Magento_Wishlist::link.phtml')->toHtml(); ?>
						<li class="minicart-li-content-show-hide">
							<?php echo $this->getChildHtml('minicart'); ?>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<div class="menu-bottom hidden-sticky nav-sections">
		<div class="container">
			<div class=" for-full-width-menu space-between center_vertical no-wrap-desktop flex-layout">
				<?php echo $this->getChildHtml("rokanthemes.horizontal.menu"); ?>
				<div class="header-static-text d-none d-xl-block hidden-sticky">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('default_header_static_text')->toHtml(); ?>
				</div>
			</div>
		</div>
	</div>
</div>